import dns from 'dns';
import fs from 'fs';

export const retry = async (fn, n) => {
  for (let i = 0; i < n; i++) {
    try {
      return await fn();
    } catch (error) {
      if (i === n - 1) {
        // propagate the last error to caller in most cases; callers may handle
        throw error;
      }
    }
  }
  return { failed: true };
};

export const getHostConfig = async (domain, lookupFn = dns.promises.lookup, retries = 3) => {
  // If a custom lookupFn is provided (non-default), keep previous behavior
  const useCustomLookup = lookupFn && lookupFn !== dns.promises.lookup;

  if (useCustomLookup) {
    const getConfig = async () => {
      const response = await lookupFn(domain);
      return { domain, ip: response && response.address ? response.address : '', ips: response && response.address ? [response.address] : [] };
    };

    try {
      const config = await retry(getConfig, retries);
      if (config && config.failed) {
        return { domain, ip: '', ips: [] };
      }
      return config;
    } catch (error) {
      return { domain, ip: '', ips: [] };
    }
  }

  // Default behavior: resolve all A and AAAA records and return them as ips array
  try {
    const [v4Res, v6Res] = await Promise.allSettled([
      dns.promises.resolve4(domain).catch(() => []),
      dns.promises.resolve6(domain).catch(() => []),
    ]);

    const v4 = v4Res.status === 'fulfilled' ? v4Res.value : [];
    const v6 = v6Res.status === 'fulfilled' ? v6Res.value : [];
    const ips = [];
    if (Array.isArray(v4)) ips.push(...v4);
    if (Array.isArray(v6)) ips.push(...v6);

    if (ips.length === 0) {
      // fallback to lookup which may use system resolver
      try {
        const fallback = await dns.promises.lookup(domain);
        if (fallback && fallback.address) {
          ips.push(fallback.address);
        }
      } catch (e) {
        // ignore
      }
    }

    return { domain, ip: ips.length > 0 ? ips[0] : '', ips };
  } catch (error) {
    return { domain, ip: '', ips: [] };
  }
};

export const resolveUrls = async (domains, lookupFn = dns.promises.lookup) => {
  const promises = domains.map((d) => getHostConfig(d, lookupFn));
  return Promise.all(promises);
};

export const generateHosts = (configs) => {
  let hostStr = "# Generated by Github Hosts start \n\n";
  configs.forEach((i) => {
    const ips = Array.isArray(i.ips) && i.ips.length > 0 ? i.ips : (i.ip ? [i.ip] : []);
    if (!ips || ips.length === 0) {
      hostStr += `# ${i.domain} update failed\n`;
    } else {
      ips.forEach((ip) => {
        const ipLen = ip ? ip.length : 0;
        const whiteLen = Math.max(1, 16 - ipLen);
        hostStr += `${ip} ${" ".repeat(whiteLen)} ${i.domain}\n`;
      });
    }
  });
  const updateTime = new Date().toLocaleString('en-US', { timeZone: 'Asia/shanghai' });
  hostStr += `\n# Last update: ${updateTime}\n`;
  return { hostStr, updateTime };
};

export const writeHosts = (hosts) => {
  try {
    const { hostStr, updateTime } = generateHosts(hosts);
    const template = fs.readFileSync('./README.template.md', 'utf-8');
    const nextReadme = template
      .toString()
      .replace('{{hosts}}', hostStr)
      .replace('{{last_update_time}}', updateTime);

    fs.writeFileSync('./hosts', hostStr);
    fs.writeFileSync('./README.md', nextReadme);

    return true;
  } catch (error) {
    throw error;
  }
};

export const generateRsc = (configs, listName = 'github-list') => {
  const header = '# Auto-generated MikroTik address list – GitHub IPs\n';
  const prefix = '/ip firewall address-list\n';

  const seen = new Set();
  const lines = [];
  configs.forEach(({ ip, ips }) => {
    const addrList = Array.isArray(ips) && ips.length > 0 ? ips : (ip ? [ip] : []);
    addrList.forEach((a) => {
      if (!a) return;
      if (seen.has(a)) return;
      seen.add(a);
      const isIPv6 = a.includes(':');
      const suffix = isIPv6 ? '/128' : '/32';
      lines.push(`add address=${a}${suffix} list=${listName}`);
    });
  });

  return header + prefix + lines.join('\n') + '\n';
};

export const generateMdnsHosts = (configs) => {
  let out = '# Auto-generated Github address list\n';
  configs.forEach(({ domain, ip, ips }) => {
    const addrList = Array.isArray(ips) && ips.length > 0 ? ips : (ip ? [ip] : []);
    if (!addrList || addrList.length === 0) {
      out += `# ${domain} resolution failed\n`;
    } else {
      addrList.forEach((a) => {
        out += `${domain} ${a}\n`;
      });
    }
  });
  return out;
};

export const writeAdditionalFiles = (configs) => {
  try {
    const rsc = generateRsc(configs);
    fs.writeFileSync('./github-ip-list.rsc', rsc);

    const mdns = generateMdnsHosts(configs);
    fs.writeFileSync('./hosts.mdns', mdns);

    // generate RouterOS DNS static records file
    const dnsRsc = generateRouterOsDns(configs);
    fs.writeFileSync('./github-dns-list.rsc', dnsRsc);

    return true;
  } catch (err) {
    throw err;
  }
};

/**
 * Generate RouterOS DNS static records in .rsc format.
 * Format example:
 * # Auto-generated MikroTik DNS list – GitHub IPs
 * /ip/dns/static>
 * add comment=github name=github.githubassets.com address=185.199.108.154
 * @param {Array<{domain: string, ip: string}>} configs
 * @returns {string}
 */
export const generateRouterOsDns = (configs) => {
  const header = '# Auto-generated MikroTik DNS list – GitHub IPs\n';
  // Use standard RouterOS CLI section header
  const prefix = '/ip dns static\n';

  const lines = [];
  const seen = new Set();
  configs.forEach(({ domain, ip, ips }) => {
    const addrList = Array.isArray(ips) && ips.length > 0 ? ips : (ip ? [ip] : []);
    if (!addrList || addrList.length === 0) {
      lines.push(`# ${domain} resolution failed`);
    } else {
      addrList.forEach((a) => {
        const key = `${domain} ${a}`;
        if (seen.has(key)) return;
        seen.add(key);
        lines.push(`add comment="github" name="${domain}" address=${a}`);
      });
    }
  });

  return header + prefix + lines.join('\n') + '\n';
};
